-- Run this in Supabase SQL Editor before using the dashboard hero uploader.
-- The current dashboard uses the public anon key, so these policies allow public
-- reads plus dashboard writes for the existing static-admin flow.

create table if not exists public.hero_images (
  id bigint generated by default as identity primary key,
  image_url text not null,
  title text,
  created_at timestamptz not null default now()
);

alter table public.hero_images
  add column if not exists sort_order integer,
  add column if not exists storage_path text;

with ordered_images as (
  select id, row_number() over (order by id) as next_sort_order
  from public.hero_images
  where sort_order is null
)
update public.hero_images
set sort_order = ordered_images.next_sort_order
from ordered_images
where public.hero_images.id = ordered_images.id;

create index if not exists hero_images_sort_order_id_idx
  on public.hero_images (sort_order, id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'hero',
  'hero',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set public = true,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

alter table public.hero_images enable row level security;

drop policy if exists "Public can read hero images" on public.hero_images;
create policy "Public can read hero images"
on public.hero_images
for select
to anon, authenticated
using (true);

drop policy if exists "Dashboard can insert hero images" on public.hero_images;
create policy "Dashboard can insert hero images"
on public.hero_images
for insert
to anon, authenticated
with check (true);

drop policy if exists "Dashboard can update hero images" on public.hero_images;
create policy "Dashboard can update hero images"
on public.hero_images
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Dashboard can delete hero images" on public.hero_images;
create policy "Dashboard can delete hero images"
on public.hero_images
for delete
to anon, authenticated
using (true);

drop policy if exists "Public can read hero storage" on storage.objects;
create policy "Public can read hero storage"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'hero');

drop policy if exists "Dashboard can upload hero storage" on storage.objects;
create policy "Dashboard can upload hero storage"
on storage.objects
for insert
to anon, authenticated
with check (bucket_id = 'hero');

drop policy if exists "Dashboard can delete hero storage" on storage.objects;
create policy "Dashboard can delete hero storage"
on storage.objects
for delete
to anon, authenticated
using (bucket_id = 'hero');

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null default 0,
  old_price numeric,
  image_url text,
  created_at timestamptz not null default now()
);

alter table public.products
  add column if not exists description text,
  add column if not exists stock integer,
  add column if not exists sizes jsonb,
  add column if not exists colors jsonb,
  add column if not exists image_url text,
  add column if not exists old_price numeric;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'products',
  'products',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set public = true,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

alter table public.products enable row level security;

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products"
on public.products
for select
to anon, authenticated
using (true);

drop policy if exists "Dashboard can insert products" on public.products;
create policy "Dashboard can insert products"
on public.products
for insert
to anon, authenticated
with check (true);

drop policy if exists "Dashboard can update products" on public.products;
create policy "Dashboard can update products"
on public.products
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Dashboard can delete products" on public.products;
create policy "Dashboard can delete products"
on public.products
for delete
to anon, authenticated
using (true);

drop policy if exists "Public can read product storage" on storage.objects;
create policy "Public can read product storage"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'products');

drop policy if exists "Dashboard can upload product storage" on storage.objects;
create policy "Dashboard can upload product storage"
on storage.objects
for insert
to anon, authenticated
with check (bucket_id = 'products');

drop policy if exists "Dashboard can delete product storage" on storage.objects;
create policy "Dashboard can delete product storage"
on storage.objects
for delete
to anon, authenticated
using (bucket_id = 'products');
